In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
%run tinyProp.py    # import all classes

In [18]:
# TESTLINEAR LAYER

tpParams = TinyPropParams(1, 1, 1, 0)   # Effectively no TinyProp

device = 'cpu'
torchLin = torch.nn.Linear(10, 6, bias=None)
tinyPropLin = TinyPropLinear(10, 6, tpParams, 1, bias=True)
x = torch.randn(1, 10)
y = x.detach().clone()
x.requires_grad = True
y.requires_grad = True

# Make sure weight and bias are the same
new_weights = torch.randn_like(torchLin.weight)
torchLin.weight = nn.Parameter(new_weights)
tinyPropLin.weight = nn.Parameter(new_weights)

new_bias = torch.randn_like(torchLin.bias)
torchLin.bias = nn.Parameter(new_bias)
tinyPropLin.bias = nn.Parameter(new_bias)

# and check that forwards produces the same result
forward = torchLin(x)
print(">LINEAR forwards:")
#print(forward)
print(">LINEAR backwards:")
forward.backward(torch.ones_like(forward))
#print(torchLin.weight.grad)
#print(torchLin.bias.grad)
print(x.grad)

forward = tinyPropLin(y)
print(">TINYPROP forwards:")
#print(forward)
print(">TINYPROP backwards:")
forward.backward(torch.ones_like(forward))
#print(tinyPropLin.weight.grad)
#print(tinyPropLin.bias.grad)
print(y.grad)

>LINEAR forwards:
>LINEAR backwards:
tensor([1., 1., 1., 1., 1., 1.])
tensor([[ 0.3872, -0.5229,  0.4562,  2.1303,  6.2382, -2.9663, -0.1808, -2.5690,
          0.5426, -0.0557]])
>TINYPROP forwards:
>TINYPROP backwards:
None
tensor([[ 0.3872, -0.5229,  0.4562,  2.1303,  6.2382, -2.9663, -0.1808, -2.5690,
          0.5426, -0.0557]])


In [23]:
# TEST CONVOLUTIONAL LAYER

tpParams = TinyPropParams(1, 1, 1, 0)   # Effectively no TinyProp

torchConv = torch.nn.Conv2d(3, 1, 3)
tinyPropConv = TinyPropConv2d(3, 1, 3, tpParams, 1)
x = torch.randn(1, 3, 12, 12)
y = x.detach().clone()
x.requires_grad = True
y.requires_grad = True

new_weights = torch.randn_like(torchConv.weight)
torchConv.weight = nn.Parameter(new_weights)
tinyPropConv.weight = nn.Parameter(new_weights)

new_bias = torch.randn_like(torchConv.bias)
torchConv.bias = nn.Parameter(new_bias)
tinyPropConv.bias = nn.Parameter(new_bias)

# and check that forwards produces the same result
forward = torchConv(x)
print(">CONV forwards:")
#print(forward)
print(">LINEAR backwards:")
forward.backward(torch.ones_like(forward))
print(torchConv.weight.grad)
print(torchConv.bias.grad)
#print(x.grad)

forward = tinyPropConv(y)
print(">TINYPROP forwards:")
#print(forward)
print(">TINYPROP backwards:")
forward.backward(torch.ones_like(forward))
print(tinyPropConv.weight.grad)
print(tinyPropConv.bias.grad)
#print(y.grad)

>CONV forwards:
>LINEAR backwards:
tensor([[[[ -9.2028,  -8.6563,  -4.5257],
          [ -9.4066,  -9.0278,  -4.8647],
          [ -4.4656,  -2.5189,   0.6910]],

         [[ -3.0408,  -5.5407,  -9.1426],
          [ -9.5581, -14.0078, -16.0899],
          [-12.8997, -14.8269, -16.8200]],

         [[ -9.9129, -10.7218,  -3.8653],
          [ -5.6023,  -8.0714,  -0.4446],
          [-12.5102, -14.4503,  -5.2304]]]])
tensor([100.])
tensor([[[[ 0.1130,  0.5018, -0.9794, -0.9794, -0.9794, -0.9794, -0.9794,
           -0.9794, -0.9794, -0.9794, -1.0924, -1.4812],
          [-1.3859, -0.1927, -1.4843, -1.4843, -1.4843, -1.4843, -1.4843,
           -1.4843, -1.4843, -1.4843, -0.0985, -1.2917],
          [-1.6668, -1.3199, -2.2342, -2.2342, -2.2342, -2.2342, -2.2342,
           -2.2342, -2.2342, -2.2342, -0.5674, -0.9143],
          [-1.6668, -1.3199, -2.2342, -2.2342, -2.2342, -2.2342, -2.2342,
           -2.2342, -2.2342, -2.2342, -0.5674, -0.9143],
          [-1.6668, -1.3199, -2.2342, -2.